import { Inter } from "next/font/google";
import "./styles/globals.css";
import Home from "./components/home.js"
import Menu from "./components/Menu.js"
import MenuInferior from "./components/menuInferior";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Home/>
        <div className="MainContainer">
          <Menu/>
          {children}
        </div>
      </body>
    </html>
  );
}
